version: '3.8'

services:
  app:
    ports:
      - 3000:3000
    container_name: app
    restart: always
    env_file:
      - .env
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next