version: '3.3'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    links:
      - mongodb
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    
  mongodb:
    image: mongo:5.0
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local