# Docker-compose overrides for local development purposes
#
# To enable overrides, copy the file into docker-compose.override.yml
version: "3.8"

services:
  app:
    volumes:
      - ".:/usr/src/app"
    ports:
      - "80:3000"

  mongodb:
    ports:
      - "27017:27017"
  