version: '3.3'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    environment: 
      - MONGODB_URI=mongodb://local_mtg:local_pass@mongodb
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    
  mongodb:
    image: mongo:5.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=local_mtg
      - MONGO_INITDB_ROOT_PASSWORD=local_pass
    ports:
      - 27017:27017