import Head from 'next/head'
import React from 'react'

export default function Home() {
  return (
    <div>
      <Head>
        <title>MTG Portfolio</title>
        <meta name="description" content="Generated by create next app" />    
      </Head>

      <main>

      </main>
    </div>
  )
}
