import axios from 'axios'
import Head from 'next/head'
import React, { useState } from 'react'
import Header from '../components/Header/Header'
import ResultList from '../components/ResultList'
import SearchForm from '../components/SearchForm'

export default function Home() {
  // const [totalCards, setTotalCards] = useState(0);
  // const [hasMore, setHasMore] = useState(false);
  // const [cardListing, setCardListing] = useState([]);

  // const findCards = async (string:string) => {
  //   const { data } = await axios(`/api/search?q=${string}`);
  //   setTotalCards(data.total_cards);
  //   setHasMore(data.has_more);
  //   setCardListing(data.data);
  // } 
  return (
    <div>
      <Head>
        <title>MTG Portfolio</title>
        <meta name="description" content="Generated by create next app" />    
      </Head>

      <main>
        {/* {totalCards > 0 && totalCards}
        <ResultList listing={cardListing} />  */}
      </main>

      <footer>
       
      </footer>
    </div>
  )
}
